# Numpy-numpy
微软专业学位课程 - 选修DAT208X
* Introduction to Python for Data Science:https://www.msaischool.com/courses/course-v1:Microsoft+DAT208x+2017_T4/about

最常用的两种类型：
* numpy.array() --- N维数组
* numpy.matrix() --- 矩阵

文档：
* 官方主页：http://www.numpy.org/
* 官方numpy教程：https://docs.scipy.org/doc/numpy/user/quickstart.html
* Python1.1.0中文手册：http://www.2xkt.com/node/1088
* Python1.1.0中文手册：https://yiyibooks.cn/xx/NumPy_v111/index.html

In [2]:
import numpy as np
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
z = x + y
print(z)

[4 4 4]


## numpy.array()
* 官方文档：https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.array.html

## 类型

In [3]:
# Create list baseball
baseball = [180, 215, 210, 210, 188, 176, 209, 200]

# Import the numpy package as np
import numpy as np

# Create a Numpy array from baseball: np_baseball
np_baseball = np.array(baseball)

# Print out type of np_baseball
print(type(np_baseball))

<class 'numpy.ndarray'>


### 基本计算

In [1]:
# height is available as a regular list
# height: http://wiki.stat.ucla.edu/socr/index.php/SOCR_Data_MLB_HeightsWeights
height = [74, 72, 73, 69]

# Import numpy
import numpy as np

# Create a Numpy array from height: np_height
np_height = np.array(height)

# Print out np_height
print(np_height)

# Convert np_height to m: np_height_m
np_height_m = np_height * 0.0254

# Print np_height_m
print(np_height_m)

[74 72 73 69]
[1.8796 1.8288 1.8542 1.7526]


In [9]:
# height and weight are available as a regular lists
# height: http://wiki.stat.ucla.edu/socr/index.php/SOCR_Data_MLB_HeightsWeights
height = [74, 72, 73, 69]
weight = [180, 210, 188, 176]

# Import numpy
import numpy as np

# Create array from height with correct units: np_height_m
np_height_m = np.array(height) * 0.0254

# Create array from weight with correct units: np_weight_kg
np_weight_kg = np.array(weight) * 0.453592

# Calculate the BMI: bmi
bmi = np_weight_kg / (np_height_m ** 2)

# Print out bmi
print(bmi)

[23.11037639 28.48080465 24.80333518 25.99036864]


In [2]:
# height and weight are available as a regular lists
# height: http://wiki.stat.ucla.edu/socr/index.php/SOCR_Data_MLB_HeightsWeights
height = [74, 72, 73, 69, 75]
weight = [180, 210, 188, 176, 165]

# Import numpy
import numpy as np

# Calculate the BMI: bmi
np_height_m = np.array(height) * 0.0254
np_weight_kg = np.array(weight) * 0.453592
bmi = np_weight_kg / np_height_m ** 2

# Print bmi
print(bmi)

# Create the light array
light = bmi < 21

# Print out light
print(light)

# Print out BMIs of all baseball players whose BMI is below 21
print(bmi[light])

[23.11037639 28.48080465 24.80333518 25.99036864 20.62335751]
[False False False False  True]
[20.62335751]


## Numpy特点

* Numpy 数组不能包含具有不同类型的元素。
* 算术运算符对常规 Python 列表和 Numpy 数组有不同的含义。

In [3]:
# Import numpy
import numpy as np

np.array([True, 1, 2]) + np.array([3, 4, False])

array([4, 5, 2])

In [36]:
areas = [11.25] + [1, 9]
print(areas)

[11.25, 1, 9]


## 子集Numpy阵列

In [37]:
# height and weight are available as a regular lists
# height: http://wiki.stat.ucla.edu/socr/index.php/SOCR_Data_MLB_HeightsWeights
height = [74, 72, 73, 69, 75]
weight = [180, 210, 188, 176, 165]

# Import numpy
import numpy as np

# Store weight and height lists as numpy arrays
np_weight = np.array(weight)
np_height = np.array(height)

# Print out the weight at index 3
print(np_weight[3])

# Print out sub-array of np_height: index 1 up to and including index 3
print(np_height[1:4])

176
[72 73 69]
