# Numpy-2D numpy阵列
微软专业学位课程 - 选修DAT208X
* Introduction to Python for Data Science:https://www.msaischool.com/courses/course-v1:Microsoft+DAT208x+2017_T4/about

最常用的两种类型：
* numpy.array() --- N维数组
* numpy.matrix() --- 矩阵

文档：
* 官方主页：http://www.numpy.org/
* 官方numpy教程：https://docs.scipy.org/doc/numpy/user/quickstart.html
* Python1.1.0中文手册：http://www.2xkt.com/node/1088
* Python1.1.0中文手册：https://yiyibooks.cn/xx/NumPy_v111/index.html

## 2D Numpy 阵列

In [1]:
# Create baseball, a list of lists
baseball = [[180, 78.4],
            [215, 102.7],
            [210, 98.5],
            [188, 75.2]]

# Import numpy
import numpy as np

# Create a 2D Numpy array from baseball: np_baseball
np_baseball = np.array(baseball)

# Print out the type of np_baseball
print(type(np_baseball))

# Print out the shape of np_baseball
print(np_baseball.shape)

<class 'numpy.ndarray'>
(4, 2)


## 子集 2D Numpy 阵列

In [17]:
# baseball is available as a regular list of lists
baseball = [[180, 78.4],
            [215, 102.7],
            [210, 98.5],
            [188, 75.2]]

# Import numpy package
import numpy as np

# Create np_baseball (2 cols)
np_baseball = np.array(baseball)

# Print out the 50th row of np_baseball
print(np_baseball[3,:])

# Select the entire second column of np_baseball: np_weight
np_weight = np_baseball[:,1]

# Print out height of 124th player
print(np_baseball[2,0])

[188.   75.2]
210.0


## 2D Numpy 算术

In [3]:
import numpy as np

np_mat = np.array([[1, 2],
                   [3, 4],
                   [5, 6]])

print(np_mat * 2)
print(np_mat + np.array([10, 10]))
print(np_mat + np_mat)

[[ 2  4]
 [ 6  8]
 [10 12]]
[[11 12]
 [13 14]
 [15 16]]
[[ 2  4]
 [ 6  8]
 [10 12]]


In [15]:
# baseball is available as a regular list of lists
# update is available as 2D Numpy array
baseball = [[74, 180, 22.99],
            [74, 215, 34.69],
            [72, 210, 30.78]]

update = [[1.2303559, -11.16224898, 1],
          [1.02614252, 16.09732309, 1],
          [1.1544228, 5.08167641, 1]]

# Import numpy package
import numpy as np

# Create np_baseball (3 cols)
np_baseball = np.array(baseball)

# Print out addition of np_baseball and update
print(np_baseball + update)

# Create Numpy array: conversion
conversion = np.array([0.0254, 0.453592, 1])

# Print out product of np_baseball and conversion
print(np_baseball * conversion)

[[ 75.2303559  168.83775102  23.99      ]
 [ 75.02614252 231.09732309  35.69      ]
 [ 73.1544228  215.08167641  31.78      ]]
[[ 1.8796  81.64656 22.99   ]
 [ 1.8796  97.52228 34.69   ]
 [ 1.8288  95.25432 30.78   ]]
